### ISSUE TITLE
support `--profile` flag in CLI

### ISSUE THREAD

**Issue by rmalecky** [aws/c3r#15]
The AWS CLI and many other cli tools support a [profiles flag](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) that allows customers to specify which profile should be used.  It would be helpful if this flag was also supported on in the c3r cli.

**Comment by pnwamk** [comment]
Thank you for the feedback! I've submitted this suggestion for internal review.

**Comment by pnwamk** [comment]
https://github.com/aws/c3r/pull/69

**Comment by pnwamk** [comment]
Merged in https://github.com/aws/c3r/pull/69 - thanks for the suggestion @rmalecky!
