### ISSUE TITLE
What Cryprography is used by C3R?

### ISSUE THREAD

**Issue by NJIT-BP397** [aws/c3r#487]
1. Since C3R serves for privacy computing and emphasizes its cryptographic security, have you ever considered other technique routes beyonds TEE, like secure multi-party computation, homomorphic encryption, or a special cryptographic PSI protocol? 
2. Will these techiniques be adopted further?

**Comment by pnwamk** [comment]
Hi @NJIT-BP397, thanks for reaching out.

The cryptography the C3R client uses is outlined in the [Cryptographic Computing for Clean Rooms](https://docs.aws.amazon.com/clean-rooms/latest/userguide/crypto-computing.html) section of the AWS Clean Rooms user guide.

For general information regarding AWS efforts in the cryptographic computing space, the [AWS Cryptographic Computing page](https://aws.amazon.com/security/cryptographic-computing/) is a great resource. This [blog post](https://aws.amazon.com/blogs/security/share-and-query-encrypted-data-in-aws-clean-rooms/) in particular introducing the cryptographic computing features of AWS Clean Rooms may be of interest.

Can we ask why you ask? Do you have a particular use-case or application in mind?
